apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  labels:
    app: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}
