image:
  repository: dajmiled/quiz-server
  tag: bb48488cae893712c30715cfdf93432458b960fb
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: quiz.localhost

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"