image:
  repository: dajmiled/quiz-server
  tag: 5159a5c5bb649ef1433e0cf2a7a5e9b5a3d515a3
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: quiz.localhost

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"