image:
  repository: dajmiled/quiz-server
  tag: fe5ab3b8057a031e10e94e8d544365df77ec79e1
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: quiz.localhost

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"